vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/build/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer